# Generated by Django 4.0.1 on 2022-01-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='create_at',
        ),
    ]
